/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntryRouteImport } from './routes/entry'
import { Route as ParkingRouteImport } from './routes/parking'
import { Route as VehiclesRouteImport } from './routes/vehicles'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryRoute = EntryRouteImport.update({
  id: '/entry',
  path: '/entry',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingRoute = ParkingRouteImport.update({
  id: '/parking',
  path: '/parking',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entry': typeof EntryRoute
  '/parking': typeof ParkingRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entry': typeof EntryRoute
  '/parking': typeof ParkingRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entry': typeof EntryRoute
  '/parking': typeof ParkingRoute
  '/vehicles': typeof VehiclesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/entry' | '/parking' | '/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/entry' | '/parking' | '/vehicles'
  id: '__root__' | '/' | '/entry' | '/parking' | '/vehicles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntryRoute: typeof EntryRoute
  ParkingRoute: typeof ParkingRoute
  VehiclesRoute: typeof VehiclesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry': {
      id: '/entry'
      path: '/entry'
      fullPath: '/entry'
      preLoaderRoute: typeof EntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parking': {
      id: '/parking'
      path: '/parking'
      fullPath: '/parking'
      preLoaderRoute: typeof ParkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntryRoute: EntryRoute,
  ParkingRoute: ParkingRoute,
  VehiclesRoute: VehiclesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
